# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fe56fb25e2f464d441e03f0c76a9c86a4653ef45c244ca4a2b7e1aafad10b19dbb8ffa2b52923d28113ad6e1b2fb6cf0e7e2926e3e9d55862bf49c28bf39afee

test:
  secret_key_base: 0d29b24567d435b0afadfb52ad4c5682f0f25c28c17aac5682bd414b84096504b5badd87636d5ae973b49094a21e37692982ce241cd1e90dbdcf45d3d8210c47

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
